# Generated by Django 3.2.11 on 2022-01-14 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.IntegerField(verbose_name='총 금액')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='cafe.customer', verbose_name='고객')),
            ],
        ),
        migrations.CreateModel(
            name='Sell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sell_at', models.DateTimeField(auto_now_add=True, verbose_name='판매일시')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sell_history', to='cafe.order', verbose_name='주문')),
                ('product', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sell_history', to='cafe.menu', verbose_name='제품')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='menu',
            field=models.ManyToManyField(related_name='order', through='cafe.Sell', to='cafe.Menu', verbose_name='주문 메뉴'),
        ),
        migrations.AddField(
            model_name='order',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='cafe.cafe', verbose_name='업장'),
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership', to='cafe.customer', verbose_name='멤버십 고객')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member', to='cafe.cafe', verbose_name='업장')),
            ],
        ),
        migrations.CreateModel(
            name='Employ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employ_date', models.DateField(verbose_name='고용일자')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employ', to='cafe.employee', verbose_name='피고용인')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employ', to='cafe.cafe', verbose_name='고용사업장')),
            ],
        ),
        migrations.AddField(
            model_name='cafe',
            name='membership',
            field=models.ManyToManyField(related_name='membership_place', through='cafe.Membership', to='cafe.Customer', verbose_name='멤버십'),
        ),
    ]
